import { createClient } from 'npm:@supabase/supabase-js@2.49.1'
import { ethers } from 'npm:ethers@6.13.5'

const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-bot-session', 'Content-Type': 'application/json' }
const routerAbi = ['function getAmountsOut(uint amountIn,address[] calldata path) external view returns (uint[] memory amounts)', 'function swapExactTokensForTokens(uint amountIn,uint amountOutMin,address[] calldata path,address to,uint deadline) external returns (uint[] memory amounts)']
const erc20Abi = ['function allowance(address owner,address spender) view returns (uint256)', 'function approve(address spender,uint256 amount) returns (bool)', 'function balanceOf(address owner) view returns (uint256)', 'function decimals() view returns (uint8)']
const env = (name: string, required = true) => { const value = Deno.env.get(name); if (required && !value) throw new Error(`Falta el secret ${name}`); return value || '' }
const json = (status: number, body: unknown) => new Response(JSON.stringify(body), { status, headers: cors })
const b64 = (value: string) => btoa(value).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '')
const unb64 = (value: string) => atob(value.replaceAll('-', '+').replaceAll('_', '/') + '='.repeat((4 - value.length % 4) % 4))
async function sign(value: string) { const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(env('BOT_SESSION_SECRET')), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); const bytes = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(value)); return b64(String.fromCharCode(...new Uint8Array(bytes))) }
async function sessionToken() { const payload = b64(JSON.stringify({ iat: Date.now(), exp: Date.now() + 8 * 60 * 60 * 1000 })); return `${payload}.${await sign(payload)}` }
async function requireSession(req: Request) { const token = req.headers.get('x-bot-session') || ''; const [payload, signature] = token.split('.'); if (!payload || !signature || signature !== await sign(payload)) throw new Error('Sesión inválida'); const data = JSON.parse(unb64(payload)); if (!data.exp || data.exp < Date.now()) throw new Error('Sesión expirada') }
function fibonacciLevels(entry: number, low: number, high: number, count: number) { if (!(low > 0 && high > low && entry >= low && entry <= high)) throw new Error('Rango inválido: lower_price < entry_price < upper_price'); const ratios = [0.236, 0.382, 0.5, 0.618, 0.786, 1].slice(0, Math.max(1, Math.min(count, 6))); return [...ratios.map(r => ({ side: 'BUY', ratio: r, price: entry - (entry - low) * r })), ...ratios.map(r => ({ side: 'SELL', ratio: r, price: entry + (high - entry) * r }))].filter(x => x.price >= low && x.price <= high).sort((a, b) => a.price - b.price) }

async function main(req: Request) {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })
  const body = await req.json().catch(() => ({}))
  const action = String(body.action || 'tick')
  if (action === 'login') { const supplied = String(body.access_key || ''); const configured = env('BOT_LOGIN_KEY'); if (!/^[A-Za-z0-9]{8}$/.test(configured) || supplied !== configured) return json(401, { ok: false, error: 'Llave incorrecta' }); return json(200, { ok: true, session: await sessionToken() }) }
  await requireSession(req)
  const supabase = createClient(env('SUPABASE_URL'), env('SUPABASE_SERVICE_ROLE_KEY'))
  const rpc = new ethers.JsonRpcProvider(env('BSC_RPC_URL'), 56)
  const wallet = new ethers.Wallet(env('TRADING_WALLET_PRIVATE_KEY'), rpc)
  const walletAddress = (env('TRADING_WALLET_ADDRESS', false) || wallet.address).toLowerCase()
  if (wallet.address.toLowerCase() !== walletAddress) throw new Error('La wallet no coincide con la llave privada')
  const routerAddress = env('PANCAKE_ROUTER_ADDRESS', false) || '0x10ED43C718714eb63d5aA57B78B54704E256024E'
  const router = new ethers.Contract(routerAddress, routerAbi, wallet)
  if (action === 'start' || action === 'stop') { const active = action === 'start'; const { error } = await supabase.from('grid_config').update({ is_active: active, updated_at: new Date().toISOString() }).eq('id', 1); if (error) throw error; return json(200, { ok: true, is_active: active, message: active ? 'Bot activado' : 'Bot detenido' }) }
  const { data: config, error } = await supabase.from('grid_config').select('*').eq('id', 1).single(); if (error || !config) throw new Error('No existe grid_config con id=1')
  const map = JSON.parse(env('PANCAKE_TOKEN_MAP_JSON')); const pair = map[config.symbol]; if (!pair || !ethers.isAddress(pair.base) || !ethers.isAddress(pair.quote)) throw new Error(`Par no configurado: ${config.symbol}`)
  const base = new ethers.Contract(pair.base, erc20Abi, wallet); const quote = new ethers.Contract(pair.quote, erc20Abi, wallet); const bd = Number(pair.baseDecimals ?? await base.decimals()); const qd = Number(pair.quoteDecimals ?? await quote.decimals()); const one = ethers.parseUnits('1', bd); const quotedOne = (await router.getAmountsOut(one, [pair.base, pair.quote]))[1]; const price = Number(ethers.formatUnits(quotedOne, qd))
  if (action === 'quote') return json(200, { ok: true, symbol: config.symbol, price })
  if (!config.is_active) return json(200, { ok: true, skipped: true, price, reason: 'Bot pausado' })
  if (env('LIVE_TRADING_ENABLED', false).toLowerCase() !== 'true') return json(200, { ok: true, dryRun: true, price, message: 'Dry-run activo' })
  const entry = Number(config.entry_price || 0); const low = Number(config.lower_price || 0); const high = Number(config.upper_price || 0); const levels = fibonacciLevels(entry, low, high, Number(config.grid_levels || 6)); const { data: state } = await supabase.from('bot_state').select('*').eq('id', 1).maybeSingle(); const first = Boolean(state?.first_buy_done); const triggered = new Set<string>(state?.triggered_levels || []); const investment = Number(config.investment_amount || 0); const percent = first ? Number(config.order_percent || 10) : Number(config.initial_order_percent || 40); const tolerance = Number(config.level_tolerance_percent || 0.15) / 100; let selected: any = null
  if (!first) { if (price > entry || price < low || price > high) return json(200, { ok: true, skipped: true, price, reason: 'Esperando entrada' }); selected = { id: 'initial', side: 'BUY', price: entry } } else { for (const level of levels) { const id = `${level.side}-${level.ratio}`; if (!triggered.has(id) && Math.abs(price - level.price) / level.price <= tolerance) { selected = { ...level, id }; break } } }
  if (!selected || investment <= 0) return json(200, { ok: true, skipped: true, price, reason: 'Sin nivel activado' })
  const slippage = Number(env('SLIPPAGE_BPS', false) || 50); if (slippage < 0 || slippage > 500) throw new Error('SLIPPAGE_BPS inválido'); const usdt = ethers.parseUnits((investment * percent / 100).toFixed(qd), qd); let amountIn: bigint; let path: string[]; let tokenIn: any
  if (selected.side === 'BUY') { amountIn = usdt; path = [pair.quote, pair.base]; tokenIn = quote } else { const balance = await base.balanceOf(walletAddress); const estimate = (await router.getAmountsOut(usdt, [pair.quote, pair.base]))[1]; amountIn = estimate < balance ? estimate : balance; path = [pair.base, pair.quote]; tokenIn = base }
  if (amountIn <= 0n) return json(200, { ok: true, skipped: true, reason: 'Balance insuficiente' }); if ((await tokenIn.allowance(walletAddress, routerAddress)) < amountIn) await (await tokenIn.approve(routerAddress, ethers.MaxUint256)).wait(); const quoteOut = (await router.getAmountsOut(amountIn, path))[1]; const minOut = quoteOut * BigInt(10000 - slippage) / 10000n; const tx = await router.swapExactTokensForTokens(amountIn, minOut, path, walletAddress, Math.floor(Date.now() / 1000) + 120); await tx.wait(); await supabase.from('bot_state').upsert({ id: 1, first_buy_done: first || selected.side === 'BUY', triggered_levels: [...triggered, selected.id], last_price: price, last_tx_hash: tx.hash, updated_at: new Date().toISOString() }); await supabase.from('grid_orders').insert({ symbol: config.symbol, order_type: selected.side, price: selected.price, amount: Number(ethers.formatUnits(amountIn, selected.side === 'BUY' ? qd : bd)), tx_hash: tx.hash, created_at: new Date().toISOString() }); return json(200, { ok: true, executed: true, side: selected.side, price, txHash: tx.hash })
}
Deno.serve(async req => { try { return await main(req) } catch (error) { console.error(error); return json(400, { ok: false, error: error instanceof Error ? error.message : 'Error desconocido' }) } })
