import { useEffect, useState } from 'react'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY)
const symbols = ['SOL/USDT', 'BTC/USDT', 'ETH/USDT', 'DOGE/USDT', 'TRX/USDT', 'ARB/USDT']

export default function App() {
  const [session, setSession] = useState(() => sessionStorage.getItem('grid_bot_session'))
  const [accessKey, setAccessKey] = useState('')
  const [loginError, setLoginError] = useState('')
  const [config, setConfig] = useState({ symbol: 'SOL/USDT', lower_price: '', upper_price: '', grid_levels: '', investment_amount: '', entry_price: '', is_active: false })
  const [orders, setOrders] = useState([])
  const [price, setPrice] = useState(null)
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(false)

  async function invoke(action, payload = {}) { const { data, error } = await supabase.functions.invoke('grid-bot', { body: { action, ...payload }, headers: session ? { 'x-bot-session': session } : {} }); if (error) throw new Error(error.message); if (data?.error) throw new Error(data.error); return data }
  async function login(event) { event.preventDefault(); setLoginError(''); setLoading(true); try { const data = await invoke('login', { access_key: accessKey }); sessionStorage.setItem('grid_bot_session', data.session); setSession(data.session); setAccessKey('') } catch (error) { setLoginError(error.message) } finally { setLoading(false) } }
  function logout() { sessionStorage.removeItem('grid_bot_session'); setSession(null); setConfig(current => ({ ...current, is_active: false })) }
  async function load() { const { data } = await supabase.from('grid_config').select('*').eq('id', 1).single(); if (data) setConfig(current => ({ ...current, ...data })); const { data: rows } = await supabase.from('grid_orders').select('*').order('created_at', { ascending: false }).limit(10); if (rows) setOrders(rows) }
  async function quote() { try { const data = await invoke('quote', { symbol: config.symbol }); setPrice(Number(data.price)) } catch (error) { setNotice(error.message) } }
  async function toggle(next) { setLoading(true); try { const data = await invoke(next ? 'start' : 'stop'); setConfig(current => ({ ...current, is_active: next })); setNotice(data.message) } catch (error) { setNotice(error.message) } finally { setLoading(false) } }
  async function save(event) { event.preventDefault(); setLoading(true); try { const { error } = await supabase.from('grid_config').update({ symbol: config.symbol, lower_price: Number(config.lower_price) || 0, upper_price: Number(config.upper_price) || 0, grid_levels: Number(config.grid_levels) || 0, investment_amount: Number(config.investment_amount) || 0, entry_price: Number(config.entry_price) || 0, is_active: config.is_active, updated_at: new Date().toISOString() }).eq('id', 1); if (error) throw error; setNotice('Configuración guardada') } catch (error) { setNotice(error.message) } finally { setLoading(false) } }
  useEffect(() => { if (session) load() }, [session]); useEffect(() => { if (session) quote() }, [session, config.symbol])
  const field = (name, value) => setConfig(current => ({ ...current, [name]: value }))

  if (!session) return <main className="login-screen"><form className="login-card" onSubmit={login}><div className="brand-mark">BG</div><h1>BitGrid Pro</h1><p>Introduce tu llave para acceder al bot.</p><input autoFocus required minLength="8" maxLength="8" pattern="[A-Za-z0-9]{8}" type="password" value={accessKey} onChange={e => setAccessKey(e.target.value)} placeholder="Llave de 8 caracteres" /><button disabled={loading}>{loading ? 'Verificando…' : 'Iniciar sesión'}</button>{loginError && <small className="login-error">{loginError}</small>}</form></main>

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">BG</div><span>BitGrid<span className="brand-accent">PRO</span></span></div><nav><a className="nav-link active">Panel General</a><a className="nav-link">Estrategias</a><a className="nav-link">Historial</a></nav><button className="logout-button" onClick={logout}>Cerrar sesión</button></aside><main className="main-content"><header className="topbar"><div><h1>Panel General</h1><p>Bot Spot Fibonacci · PancakeSwap</p></div><div className="price-ticker">{config.symbol} · {price ? `$${price.toLocaleString()}` : '—'}</div></header><section className="status-banner"><div><b>Bot {config.is_active ? 'ACTIVO' : 'PAUSADO'}</b><p>{config.is_active ? 'Estrategia ejecutándose' : 'Listo para configurar'}</p></div><button onClick={() => toggle(!config.is_active)} disabled={loading}>{config.is_active ? 'Pausar bot' : 'Activar bot'}</button></section><section className="stats-grid"><div className="stat-card"><span>Capital invertido</span><strong>{Number(config.investment_amount || 0).toLocaleString()} USDT</strong></div><div className="stat-card"><span>Precio actual</span><strong>{price ? `$${price.toLocaleString()}` : '—'}</strong></div><div className="stat-card"><span>Órdenes</span><strong>{orders.length}</strong></div></section><section className="panel config-panel"><h2>Configurar estrategia</h2><form onSubmit={save} className="form-grid"><label>Par<select value={config.symbol} onChange={e => field('symbol', e.target.value)}>{symbols.map(item => <option key={item}>{item}</option>)}</select></label><label>Precio inferior<input type="number" step="any" value={config.lower_price} onChange={e => field('lower_price', e.target.value)} /></label><label>Precio de entrada<input type="number" step="any" value={config.entry_price} onChange={e => field('entry_price', e.target.value)} /></label><label>Precio superior<input type="number" step="any" value={config.upper_price} onChange={e => field('upper_price', e.target.value)} /></label><label>Niveles<input type="number" value={config.grid_levels} onChange={e => field('grid_levels', e.target.value)} /></label><label>Inversión USDT<input type="number" step="any" value={config.investment_amount} onChange={e => field('investment_amount', e.target.value)} /></label><button disabled={loading}>Guardar configuración</button>{notice && <p>{notice}</p>}</form></section><section className="panel"><h2>Actividad reciente</h2>{orders.length ? orders.map(row => <div className="order-row" key={row.id}>{row.order_type} · {row.price} USDT · {row.amount}</div>) : <p>Sin órdenes registradas.</p>}</section></main></div>
}
